EmployeeLoanManagementSystem/EmployeeLoanManagementSystem/Controllers/HRController.cs
using EmployeeLoanManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CrystalDecisions.CrystalReports.Engine;
using System.IO;

namespace EmployeeLoanManagementSystem.Controllers
{
    public class HRController : Controller
    {
        // public int ide;
         SqlConnection conn = new SqlConnection("Data Source=DESKTOP-R6RA1PL\\TOOBAASIF;Initial Catalog=DB7;User ID=sa;Password=1212;MultipleActiveResultSets=True;Application Name=EntityFramework");
     
        DB7Entities4 db = new DB7Entities4();
        // GET: HR
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Welcome()
        {
            return View();
        }

        // GET: HR/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        //employee details who applied for loan
        public static int empid;
        public static int loanid;
        [HttpGet]
        
        public ActionResult Edetails(int ide, int idee)
        {
            empid = ide;
            loanid = idee;
            List<string> l = new List<string>();
            string r = "Request Status";
            string q = "select Value from Lookup where Category = '"+r+"'";
            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
            SqlCommand cmd = new SqlCommand(q, conn);
            SqlDataReader reader = cmd.ExecuteReader();
            string value = "0";
          //  int i = 0;
            while (reader.Read())
            {
                value = (reader[0].ToString());
                //   l[i] = value;
                l.Add(value);
             
               // i++;
            }
            DB7Entities4 db = new DB7Entities4();
            Lookup db1 = new Lookup();
            ViewBag.choice = new SelectList(l);
          //s  choice.SelectedValue = l.Attributes("InitialValue");
            var getRequestStatus = db.LoanRequestStatus.ToList();
            SelectList list = new SelectList(getRequestStatus, "LoanId", "RequestStatus");
            ViewBag.requeststatus = list;

            DataTable dt = new DataTable();
            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
            string query1 = "select Employee.Id,LoanApply.LoanApplyId,FirstName +' '+ LastName as [Name], Email,Department.Name,Designation,Salary,HireDate,RequestDate,LoanMoney,NoOfInstallments,InstallmentStartDate,InstallmentEndDate,RequestDate from Employee Join LoanApply on Employee.Id = LoanApply.EmployeeId join LoanRequestStatus on LoanApply.LoanApplyId =  LoanRequestStatus.LoanId join Department on Department.Id = Employee.DepartmentId where RequestStatus = 'Pending' and Employee.Id = '" + ide + "' and  LoanApplyId = '" + idee + "'";
            SqlDataAdapter da = new SqlDataAdapter(query1, conn);
            da.Fill(dt);
            return View(dt);
        }




        private int instalno(int l)
        {
            string query;
            string r = "Pending";
            query = "select NoOfInstallments from LoanApply join LoanRequestStatus on LoanRequestStatus.LoanId = LoanApply.LoanApplyId where RequestStatus = '"+r+"' AND LoanApplyId = '" + l + "' ";


            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
            SqlCommand cmd = new SqlCommand(query, conn);
            SqlDataReader reader = cmd.ExecuteReader();
            int value = 0;
            while (reader.Read())
            {
                value = int.Parse((reader[0].ToString()));
            }
            return value;
        }


        [HttpPost, ActionName("Edetails")]
        [ValidateAntiForgeryToken]
        public ActionResult EdetailsConfirmed(FormCollection collection)
        {
            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
            int ide = empid;
            int idee = loanid;
            int instalnum = instalno(idee);

            string choice = collection["choice"].ToString();
            string reason = collection["reason"].ToString();

            DateTime dt = DateTime.Now;
            DateTime startdate = new DateTime(dt.AddMonths(1).Year, dt.AddMonths(1).Month, 1);

            DateTime enddate = DateTime.Now.AddMonths(instalnum);
            DateTime sub = DateTime.Now;
            string qry = "update LoanRequestStatus set RespondDate='" + sub + "',RequestStatus='" +choice+ "',Reason='"+reason+"' where LoanId = '" + idee + "'";
            //  string qry = "insert into LoanDocumentVerify(PropertyDocument)values('"+image1+ "') select * from LoanDocumentVerify where LoanId = '" + ide+"'";
            SqlCommand sc = new SqlCommand(qry, conn);
            int i = sc.ExecuteNonQuery();
            if (choice == "Accepted")
            {
                string cid = "N";
                string qry1 = "update LoanApply set InstallmentStartDate='" + startdate + "',InstallmentEndDate='" + enddate + "' where LoanApplyId = '" + idee + "'";
                SqlCommand sc1 = new SqlCommand(qry1, conn);
                int j = sc1.ExecuteNonQuery();
                for(int p=1;p<=instalnum;p++)
                {
                    string qry2 = "insert into Installment(LoanId,InstallmentsNo,InstallmentDate,IsPaid) Values('"+idee+ "','" +p+ "','" + startdate + "','" +cid+ "')  ";
                    SqlCommand sc2 = new SqlCommand(qry2, conn);
                    int k = sc2.ExecuteNonQuery();
                    startdate = new DateTime(startdate.AddMonths(1).Year, startdate.AddMonths(1).Month, 1);
                }
            }

           
            return RedirectToAction("Welcome");
        }


        // GET: HR/Create
        public ActionResult Create()
        {
            return View();
        }
        //Pending Requests
        public ActionResult PendingRequest()
        {

            DataTable dt = new DataTable();
            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }

            string a = "Pending";
            string q;
            q = "select Employee.Id,LoanApply.LoanApplyId, FirstName +' '+ LastName as [Name], Email,LoanMoney,LoanApply.[RequestDate],LoanCategory.Type from Employee Join LoanApply on Employee.Id = LoanApply.EmployeeId join LoanCategory on LoanApply.LoanCategory = LoanCategory.Id  join LoanRequestStatus on LoanApply.LoanApplyId =  LoanRequestStatus.LoanId where RequestStatus ='" + a + "'";

            SqlDataAdapter da = new SqlDataAdapter(q, conn);
            da.Fill(dt);
            // r data = db.LoanApplies.SqlQuery(query).ToList();
            return View(dt);
        }
        public ActionResult viewreq(int ide)
        {
            DataTable dt = new DataTable();
            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }

             string q;
            q = "select Employee.Id,LoanApply.LoanApplyId, FirstName +' '+ LastName as [Name], Email,Salary,Department.Name,Designation,HireDate,LoanCategory.Type,LoanMoney,RequestDate,NoOfInstallments,[Installment Money],LoanAgreement,RequestStatus,Reason,RespondDate from Employee Join Department on Department.Id= Employee.DepartmentId  Join LoanApply on Employee.Id = LoanApply.EmployeeId JOIN LoanCategory ON LoanCategory.Id = LoanApply.LoanCategory join LoanRequestStatus on LoanApply.LoanApplyId =  LoanRequestStatus.LoanId where LoanApplyId = '" + ide+"'";

            SqlDataAdapter da = new SqlDataAdapter(q, conn);
            da.Fill(dt);

            // r data = db.LoanApplies.SqlQuery(query).ToList();
            return View(dt);

        }
        public ActionResult AcceptRequest()
        {
            DataTable dt = new DataTable();
            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }

            string a = "Accepted";
            string q;
            q = "select Employee.Id,LoanApply.LoanApplyId, FirstName +' '+ LastName as [Name], Email,LoanMoney,LoanApply.[RequestDate],LoanCategory.Type from Employee Join LoanApply on Employee.Id = LoanApply.EmployeeId join LoanCategory on LoanApply.LoanCategory = LoanCategory.Id join LoanRequestStatus on LoanApply.LoanApplyId =  LoanRequestStatus.LoanId where RequestStatus ='" + a + "'";

            SqlDataAdapter da = new SqlDataAdapter(q, conn);
            da.Fill(dt);

            // r data = db.LoanApplies.SqlQuery(query).ToList();
            return View(dt);


        }
        public ActionResult AcceptRequestinstal()
        {
            DataTable dt = new DataTable();
            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }

            string a = "Accepted";
            string q;
            q = "select Employee.Id,LoanApply.LoanApplyId, FirstName +' '+ LastName as [Name], Email,Department.Name,Designation,LoanMoney,NoOfInstallments,LoanApply.[RequestDate],LoanCategory.Type from Employee Join Department on Employee.DepartmentId = Department.Id  Join LoanApply on Employee.Id = LoanApply.EmployeeId join LoanCategory on LoanApply.LoanCategory = LoanCategory.Id join LoanRequestStatus on LoanApply.LoanApplyId =  LoanRequestStatus.LoanId where RequestStatus ='" + a + "'";

            SqlDataAdapter da = new SqlDataAdapter(q, conn);
            da.Fill(dt);

            // r data = db.LoanApplies.SqlQuery(query).ToList();
            return View(dt);

        }
        public ActionResult employeeloan()
        {
            DataTable dt = new DataTable();
            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }

            string a = "Accepted";
            string q;

EmployeeLoanManagementSystem/EmployeeLoanManagementSystem/Views/HR/AcceptRequest.cshtml
@model System.Data.DataTable

@{
    ViewBag.Title = "AcceptRequest";
}
<head>
    <style>
        nav.navbar.bootsnav.navbar-fixed {
            overflow: scroll;
            height: 100%;
        }
    </style>
</head>
<h2 style="padding-top:100px;text-align:center">Employee Against Accepted Requests</h2>
<table class="table table-bordered table-striped">
    <tr>
        <th style="display:none;">
            Id
        </th>
        <th style="display:none;">LoanApplyId</th>
        <th>Name</th>
        <th>Email</th>
        <th>Loan Money</th>
        <th>Request Date</th>
        <th>Loan Category</th>
        <th>Edit Response</th>
        <th>View Details</th>
        <th>View Installments</th>
    </tr>
    @for (int i = 0; i < Model.Rows.Count; i++)
    {
    <tr>
        <td style="display:none;">
            @Model.Rows[i][0]
        </td>
        <td style="display:none;">@Model.Rows[i][1]</td>
        <td>@Model.Rows[i][2]</td>
        <td>@Model.Rows[i][3]</td>
        <td>@Model.Rows[i][4]</td>
        <td>@Model.Rows[i][5]</td>
        <td>@Model.Rows[i][6]</td>
        <td>@Html.ActionLink("Details", "viewreq", new { @ide = @Model.Rows[i][1] }, null)</td>
        <td>@Html.ActionLink("Edit Response", "Edetails", new { @ide = @Model.Rows[i][0], @idee = @Model.Rows[i][1] }, null)</td>
        <td>@Html.ActionLink("View Installments", "instal", new { @ide = @Model.Rows[i][0], @idee = @Model.Rows[i][1] }, null)</td>

    </tr>
    }
</table>

EmployeeLoanManagementSystem/EmployeeLoanManagementSystem/Views/HR/AcceptRequestinstal.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "AcceptRequestinstal";
}

<head>
    <style>
        nav.navbar.bootsnav.navbar-fixed {
            overflow: scroll;
            height: 100%;
        }
    </style>
</head>
<h2 style="padding-top:100px;text-align:center">Installments Reports</h2>
<table class="table table-bordered table-striped">
    <tr>
        <th style="display:none;">
            Id
        </th>
        <th style="display:none;">LoanApplyId</th>
        <th>Name</th>
        <th>Email</th>
        <th>Department Name</th>
        <th>Designation</th>
        <th>Loan Money</th>
        <th>Number Of Installments</th>
        <th>Request Date</th>
        <th>Loan Category</th>

        <th>All Installments</th>
        <th>Paid Installments</th>
        <th>UnPaid Installments</th>
    </tr>
    @for (int i = 0; i < Model.Rows.Count; i++)
    {
    <tr>
        <td style="display:none;">
            @Model.Rows[i][0]
        </td>
        <td style="display:none;">@Model.Rows[i][1]</td>
        <td>@Model.Rows[i][2]</td>
        <td>@Model.Rows[i][3]</td>
        <td>@Model.Rows[i][4]</td>
        <td>@Model.Rows[i][5]</td>
        <td>@Model.Rows[i][6]</td>
        <td>@Model.Rows[i][7]</td>
        <td>@Model.Rows[i][8]</td>
        <td>@Model.Rows[i][9]</td>
        <td>@Html.ActionLink("Installments Report", "installments", new {  @idee = @Model.Rows[i][1] }, null)</td>
        <td>@Html.ActionLink("Installments Report", "paidinstallments", new { @idee = @Model.Rows[i][1] }, null)</td>
        <td>@Html.ActionLink("Installments Report", "unpaidinstallments", new { @idee = @Model.Rows[i][1] }, null)</td>
       
    </tr>
    }
</table>

EmployeeLoanManagementSystem/EmployeeLoanManagementSystem/Views/HR/Edetails.cshtml
@model System.Data.DataTable
@{
    /**/

    ViewBag.Title = "Edetails";
}

<head>
    <style>
        nav.navbar.bootsnav.navbar-fixed {
            overflow: scroll;
            height: 100%;
        }
    </style>
</head>
@Html.BeginForm("Edetails", "HR", FormMethod.Post)
 {                           
@Html.AntiForgeryToken()

<body>




    <h2 style="padding-top:80px;text-align:center">Response To Requests</h2>

    <div class="container">
        <table class="table table-bordered table-striped" style="align-content:center">

            @for (int i = 0; i < Model.Rows.Count; i++)
            {
                <tr>
                    <th style="display:none;">LoanApplyId: </th>
                    <td style="display:none;">@Model.Rows[i][0]</td>
                </tr>
                <tr>
                    <th style="display:none;">EmployeeId: </th>
                    <td style="display:none;">@Model.Rows[i][1]</td>
                </tr>
                <tr>
                    <th>Name:</th>
                    <td>@Model.Rows[i][2]</td>
                </tr>
                <tr>
                    <th>Email:</th>
                    <td>@Model.Rows[i][3]</td>
                </tr>
                <tr>
                    <th>Department:</th>
                    <td>@Model.Rows[i][4]</td>
                </tr>
                <tr>
                    <th>Designation:</th>
                    <td>@Model.Rows[i][5]</td>
                </tr>
                <tr>
                    <th>Salary:</th>
                    <td>@Model.Rows[i][6]</td>
                </tr>
                <tr>
                    <th>Hire Date:</th>
                    <td>@Model.Rows[i][7]</td>
                </tr>
                <tr>
                    <th>Request Date:</th>
                    <td>@Model.Rows[i][8]</td>
                </tr>
                <tr>
                    <th>Loan Money</th>
                    <td>@Model.Rows[i][9]</td>
                </tr>
                <tr>
                    <th>Number Of Installments:</th>
                    <td>@Model.Rows[i][10]</td>
                </tr>
                <tr>
                    <th>Installment Start Date:</th>
                    <td>@Model.Rows[i][11]</td>
                </tr>
                <tr>
                    <th>Installment End Date:</th>
                    <td>@Model.Rows[i][12]</td>
                </tr>

                <tr>
                    <th>Request Status:</th>
                    <td>  @Html.DropDownList("choice")</td>
                </tr>
                <tr>
                    <th>Reason Of Respond:</th>
                    <td>   <input type="text" name="Reason" style="font-size: 20px;height:50px;width:900px" /></td>
                </tr>
            }
        </table>
        <br />
        <div class="form-group">
            @*  @Html.DropDownList("Request Status", ViewBag.choice as SelectList, "Pending")
                    @Html.DropDownList("choice", "Request Status")
                    <h5>Reason:</h5>
                    <input type="text" name="Reason" style="font-size: 20px;height:50px;width:550px" />
                </div>*@
            <div >

                <input type="submit" class="btn btn-default" style="font-family:Arial;font-size:12px;height:50px;width:160px"  value="Submit" />

            </div>
        </div>

</body>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EmployeeLoanManagementSystem/EmployeeLoanManagementSystem/Views/HR/Welcome.cshtml
@{
    ViewBag.Title = "Welcome";
}


<head>
    <style type="text/css">
        <meta name="viewport" content="width=device-width, initial-scale=1" >
        <style >
        * {
            box-sizing: border-box;
        }

        body {
            font-family: Verdana, sans-serif;
        }

        .mySlides {
            display: none;
        }

        img {
            vertical-align: middle;
        }

        /* Slideshow container */
        .slideshow-container {
            max-width: 1000px;
            position: relative;
            margin: auto;
        }

        /* Caption text */
        .text {
            color: #f2f2f2;
            font-size: 15px;
            padding: 8px 12px;
            position: absolute;
            bottom: 8px;
            width: 100%;
            text-align: center;
        }

        /* Number text (1/3 etc) */
        .numbertext {
            color: #f2f2f2;
            font-size: 12px;
            padding: 8px 12px;
            position: absolute;
            top: 0;
        }

        /* The dots/bullets/indicators */
        .dot {
            height: 15px;
            width: 15px;
            margin: 0 2px;
            background-color: #bbb;
            border-radius: 50%;
            display: inline-block;
            transition: background-color 0.6s ease;
        }

        .active {
            background-color: #717171;
        }

        /* Fading animation */
        .fade {
            -webkit-animation-name: fade;
            -webkit-animation-duration: 1.5s;
            animation-name: fade;
            animation-duration: 1.5s;
        }

        @@-webkit-keyframes fade {
            from {
                opacity: .4
            }

            to {
                opacity: 1
            }
        }

        @@keyframes fade {
            from {
                opacity: .4
            }

            to {
                opacity: 1
            }
        }

        /* On smaller screens, decrease text size */
        @@media only screen and (max-width: 300px) {
            .text {
                font-size: 11px
            }
        }

        body {
        }

        .container {
            overflow: auto;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        nav.navbar.bootsnav.navbar-fixed {
            overflow: scroll;
            height: 100%;
        }

        ::-webkit-scrollbar-thumb {
            border-radius: 4px;
            background-color: rgba(0,0,0,.5);
            -webkit-box-shadow: 0 0 1px rgba(255,255,255,.5);
        }

        .a:hover, .dropdown-btn:hover {
            background-color: #009688;
        }

        .w3-teal {
            height: 50px;
        }

        .btn.hover, .dropdown-btn:hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }
        .req.hover {
            background-color: #009688;
        }
        .btn-danger {
            border-radius: 0px;
        }
        /* Style the sidenav links and the dropdown button */
        .dropdown-btn {
            padding: 6px 8px 6px 16px;
            text-decoration: none;
            font-size: 20px;
            color: #818181;
            display: block;
            border: none;
            background: none;
            width: 100%;
            text-align: left;
            cursor: pointer;
            outline: none;
        }
        /* On mouse-over
            .sidenav a:hover, .dropdown-btn:hover {
                color: #f1f1f1;
            }*/
        /* Add an active class to the active dropdown button */
        .active {
            background-color: #009688;
            color: white;
        }

        /* Dropdown container (hidden by default). Optional: add a lighter background color and some left padding to change the design of the dropdown content */
        .dropdown-container {
            display: none;
            /*background-color: #262626;*/
            padding-left: 8px;
        }

        /* Optional: Style the caret down icon */
        .fa-caret-down {
            float: right;
            padding-right: 8px;
        }
    </style>

</head>


<h2 style="padding-top:50px;padding-left:300px;color:#009688">WELCOME TO LOAN PROVIDER SYSTEM</h2>
<!DOCTYPE html>
<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>

    <div class="w3-sidebar w3-bar-block w3-card w3-animate-left" style="display:none;height:500px" id="mySidebar">
        <button class="w3-bar-item w3-button w3-large"
                onclick="w3_close()">

            Close &times;

        </button>
        <br />
        <button class="dropdown-btn">
            View Requests
            <i class="fa fa-caret-down"></i>
        </button>
        <div class="dropdown-container">
            <a href=@Url.Action("PendingRequest","HR")>
                <div class="req">
                    <br />
                    <br />
                    Pending Requests
                    <br />
                    <br />
                </div>
            </a>
            <a href=@Url.Action("AcceptRequest","HR")>
                <div class="req">
                    Accepted Requests
                    <br />
                    <br />
                </div>
            </a>
            <a href=@Url.Action("RejectRequest","HR")>
                <div class="req">
                    Rejected Requests
                    <br />
                    <br />
                </div>
            </a>
        </div>
        <br />
        <br />
        <a href=@Url.Action("loanpolicies","loan") class="a">Loan Policies</a><br><br><br>
        <a href=@Url.Action("instructions","loan") class="a">Instructions For Loan</a><br><br><br>
        <a href=@Url.Action("prodocuments","HR") class="a">Instructions For Loan</a><br><br><br>
        <a href=@Url.Action("Index","Account") class="a">View Registered Employees</a><br><br><br>
        <a href=@Url.Action("Register","Account") class="a">Add a New Employee</a><br><br><br>

    </div>

    <div id="main">

        <div class="w3-teal">
            <button id="openNav" class="w3-button w3-teal w3-xlarge" style="" onclick="w3_open()">&#9776;</button>
            <div class="w3-container">
                @*<h3 style="padding-top:50px">LOAN PROVIIDER</h3>*@
            </div>
        </div>

        <div style="display:flex;font-size:0px">
            <div style="padding-right:0px">
                <img style="height:200px;width:290px" src="/images/kang5.jpg">
            </div>
            <div style="padding-left:0px">
                <img style="height:200px;width:285px" src="/images/kang6.jpg">
            </div>
            <div style="padding-left:0px">
                <img style="height:200px;width:280px" src="/images/kang7.jpg">
            </div>
            <div style="padding-left:0px">
                <img style="height:200px;width:290px" src="/images/kang4.jpg">
            </div>
        </div>

        <div class="w3-container">
            <b>
                <p style="font-size:16px ;color: #009688">
                    Syspro is providing interest free loan. Get loan on easy installments<br />
                    View our loan policies, apply for loan, view loan history and loan request status.<br />
                    The employee need to read the instructions and policies properly before applying for loan
                </p>
            </b>
        </div>

    </div>

    <script>
        function w3_open() {
            document.getElementById("main").style.marginLeft = "25%";
            document.getElementById("mySidebar").style.width = "25%";
            document.getElementById("mySidebar").style.display = "block";
            document.getElementById("openNav").style.display = 'none';
        }
        function w3_close() {
            document.getElementById("main").style.marginLeft = "0%";
            document.getElementById("mySidebar").style.display = "none";
            document.getElementById("openNav").style.display = "inline-block";
        }
    </script>
    <script>
        /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
        var dropdown = document.getElementsByClassName("dropdown-btn");
        var i;

        for (i = 0; i < dropdown.length; i++) {
            dropdown[i].addEventListener("click", function () {
                this.classList.toggle("active");
                var dropdownContent = this.nextElementSibling;
                if (dropdownContent.style.display === "block") {
                    dropdownContent.style.display = "none";
                } else {
                    dropdownContent.style.display = "block";
                }
            });
        }
    </script>

</body>
</html>

EmployeeLoanManagementSystem/EmployeeLoanManagementSystem/Views/HR/prodocumentsverify.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "prodocumentsverify";
}
<head>
    <style>
        nav.navbar.bootsnav.navbar-fixed {
            overflow: scroll;
            height: 100%;
        }
    </style>
</head>
@Html.BeginForm("prodocumentsverify", "HR", FormMethod.Post)
 {
@Html.AntiForgeryToken()

<body>




    <h2 style="padding-top:80px;text-align:center">Provident Fund Documents</h2>

    <div class="container">
        <table class="table table-bordered table-striped" style="align-content:center">

            @for (int i = 0; i < Model.Rows.Count; i++)
            {
                <tr>
                    <th style="display:none;">LoanApplyId: </th>
                    <td style="display:none;">@Model.Rows[i][0]</td>
                </tr>
                <tr>
                    <th style="display:none;">EmployeeId: </th>
                    <td style="display:none;">@Model.Rows[i][1]</td>
                </tr>
                <tr>
                    <th>Name:</th>
                    <td>@Model.Rows[i][2]</td>
                </tr>
                <tr>
                    <th>Email:</th>
                    <td>@Model.Rows[i][3]</td>
                </tr>
                <tr>
                    <th>Loan Money:</th>
                    <td>@Model.Rows[i][4]</td>
                </tr>
                <tr>
                    <th>Request Date:</th>
                    <td>@Model.Rows[i][5]</td>
                </tr>
                <tr>
                    <th>Property Document</th>
                    <td>
                        @if (@Model.Rows[i][10].ToString() != "")
                        {
                            string s = @Model.Rows[i][10].ToString();






                            <a href="@s" style="height:100%;width:100%">
                                <centre> <img align="middle" src="@s" style="height:150px;width:250px"></centre>
                            </a>

                        }
                    </td>
                </tr>
                <tr>
                    <th>Automobile Document</th>
                    <td>
                        @if (@Model.Rows[i][11].ToString() != "")
                        {
                            string s = @Model.Rows[i][11].ToString();






                            <a href="@s" style="height:100%;width:100%">
                                <centre> <img align="middle" src="@s" style="height:150px;width:250px"></centre>
                            </a>

                        }
                    </td>
                    </tr>
                <tr>
                    <th>Submission Date:</th>
                    <td>@Model.Rows[i][12]</td>
                </tr>
                <tr>
                    <th>Is Defaulter:</th>
                    <td>@Model.Rows[i][13]</td>
                </tr>

                <tr>
                    <th>Documents Status:</th>
                    <td>  @Html.DropDownList("choice")</td>
                </tr>
                <tr>
                    <th>Reason Of Respond:</th>
                    <td>   <input type="text" name="Reason" style="font-size: 20px;height:50px;width:900px" /></td>
                </tr>
                
            }
        </table>
        <br />
        <div class="form-group">
            @*  @Html.DropDownList("Request Status", ViewBag.choice as SelectList, "Pending")
            @Html.DropDownList("choice", "Request Status")
            <h5>Reason:</h5>
            <input type="text" name="Reason" style="font-size: 20px;height:50px;width:550px" />
        </div>*@
            <div>

                <input type="submit" class="btn btn-default" style="font-family:Arial;font-size:12px;height:50px;width:160px" value="Submit" />

            </div>
        </div>

</body>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>