EmployeeLoanManagementSystem/EmployeeLoanManagementSystem/Models/Installment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeLoanManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installment
    {
        public int InstallmentId { get; set; }
        public int LoanId { get; set; }
        public Nullable<int> InstallmentsNo { get; set; }
        public Nullable<System.DateTime> InstallmentDate { get; set; }
        public string IsPaid { get; set; }
    
        public virtual LoanApply LoanApply { get; set; }
    }
}

EmployeeLoanManagementSystem/EmployeeLoanManagementSystem/Controllers/loanController.cs
using EmployeeLoanManagementSystem.Models;

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Runtime.Serialization.Formatters.Binary;
using System.Runtime.Serialization;
using System.Net;


namespace EmployeeLoanManagementSystem.Controllers
{
    public class loanController : Controller
    {
        // public int ide;
        public static int docid;
        SqlConnection conn = new SqlConnection("Data Source=DESKTOP-R6RA1PL\\TOOBAASIF;Initial Catalog=DB7;User ID=sa;Password=1212;MultipleActiveResultSets=True;Application Name=EntityFramework");
        private DB7Entities4 db = new DB7Entities4();
        // GET: loan
        public ActionResult Index()
        {
            return View();
        }
        private int emp_id(string email1)
        {
            string query;
           
            query = "SELECT Id FROM Employee WHERE  Email ='" + email1 + "' ";

            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
            SqlCommand cmd = new SqlCommand(query, conn);
            SqlDataReader reader = cmd.ExecuteReader();
            int value = 0;
            while (reader.Read())
            {
                value = int.Parse(reader[0].ToString());
            }
            return value;
        }
        private int RetrieveID()
        {
            int value = 0;
            try
            {
                string query = " Select LoanApplyId  from LoanApply where (LoanApplyId = SCOPE_IDENTITY());";
                if (conn.State == ConnectionState.Closed)
                {
                    conn.Open();
                }
                SqlCommand cmd = new SqlCommand(query, conn);
                var val = cmd.ExecuteScalar().ToString();
                value = int.Parse(val);

            }
            catch (Exception ex)
            {
                throw;
            }


            return value;
        }
        private int cat_id(string email1)
        {
            string query;

            query = "SELECT Id FROM LoanCategory WHERE  Type ='" + email1 + "' ";


            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
            SqlCommand cmd = new SqlCommand(query, conn);
            SqlDataReader reader = cmd.ExecuteReader();
            int value = 0;
            while (reader.Read())
            {
                value = int.Parse(reader[0].ToString());
            }
            return value;
        }
        private string loanprop(int l)
        {
            string query;

            query = "SELECT LoanForProperty FROM LoanApply WHERE  LoanApplyId ='" + l + "' ";


            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
            SqlCommand cmd = new SqlCommand(query, conn);
            SqlDataReader reader = cmd.ExecuteReader();
            string value = "0";
            while (reader.Read())
            {
                value = (reader[0].ToString());
            }
            return value;
        }
        private int getsal(string email)
        {
            string query;

            query = "SELECT Salary FROM Employee WHERE  Email ='" + email + "' ";


            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
            SqlCommand cmd = new SqlCommand(query, conn);
            SqlDataReader reader = cmd.ExecuteReader();
            int value = 0;
            while (reader.Read())
            {
                value = int.Parse(reader[0].ToString());
            }
            return value;
        }
        private int getpro(string email)
        {
            string query;

            query = "SELECT ProvidentFundAmount FROM Employee WHERE  Email ='" + email + "' ";


            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
            SqlCommand cmd = new SqlCommand(query, conn);
            SqlDataReader reader = cmd.ExecuteReader();
            int value = 0;
            while (reader.Read())
            {
                value = int.Parse(reader[0].ToString());
            }
            return value;
        }
        private string loanauto(int l)
        {
            string query;

            query = "SELECT LoanForAutomobile FROM LoanApply WHERE  LoanApplyId ='" + l + "' ";


            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
            SqlCommand cmd = new SqlCommand(query, conn);
            SqlDataReader reader = cmd.ExecuteReader();
            string value = "0";
            while (reader.Read())
            {
                value = (reader[0].ToString());
            }
            return value;
        }
        private string stat(int l)
        {
            string query;

            query = "select Status from LoanDocumentVerify  where LoanId = '" + l + "' ";


            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
            SqlCommand cmd = new SqlCommand(query, conn);
            SqlDataReader reader = cmd.ExecuteReader();
            string value = "0";
            while (reader.Read())
            {
                value = ((reader[0].ToString()));
            }
            return value;
        }
        private int instalno(int l)
        {
            string query;

           query = "select NoOfInstallments from LoanApply join LoanRequestStatus on LoanRequestStatus.LoanId = LoanApply.LoanApplyId where RequestStatus = Accepted AND LoanId = '" + l + "' ";


            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
            SqlCommand cmd = new SqlCommand(query, conn);
            SqlDataReader reader = cmd.ExecuteReader();
            int value = 0;
            while (reader.Read())
            {
                value = int.Parse((reader[0].ToString()));
            }
            return value;
        }
        // GET: loan/Details/5
        public ActionResult Details(int ide)
        {
            return View();
        }
        public ActionResult welcome()
        {
            return View();
        }
        public ActionResult loanpolicies()
        {
            return View();
        }
        [HttpGet]
        public ActionResult documentsverification(int ide)
        {
            //LoanRequestStatu l = db.LoanRequestStatus.Find(ide);
            docid = ide;
           
            return View();
        }
      
        public ActionResult installments(int ide)

        {
            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
            string s = "select InstallmentId,LoanId,InstallmentsNo,InstallmentDate,[Installment Money],IsPaid from Installment join LoanApply on LoanApply.LoanApplyId = Installment.LoanId   where LoanId = '" + ide+"' ";
            DataTable dt = new DataTable();
            SqlDataAdapter da = new SqlDataAdapter(s, conn);
            da.Fill(dt);

            return View(dt);
        }
        public ActionResult loanstat()
        {
            return View();
        }
      
        public ActionResult instructions()
        {
            return View();
        }
        public ActionResult provident()
        {
            string s = "Against Provident Fund";
            int cat = cat_id(s);
            DataTable dt = new DataTable();
            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
            string query = "SELECT LoanApplyId,LoanMoney,RequestDate,LoanForProperty,LoanForAutomobile from LoanApply JOIN LoanRequestStatus ON LoanRequestStatus.LoanId = LoanApply.LoanApplyId JOIN LoanCategory on LoanCategory.Id=LoanApply.LoanCategory JOIN Employee on Employee.Id = LoanApply.EmployeeId  where LoanCategory='" + cat + "' AND Employee.Email ='" + User.Identity.Name.ToString() + "'";
            //va
            string query1 = "SELECT LoanApplyId,LoanMoney,RequestDate,RequestStatus,Reason,LoanForProperty,LoanForAutomobile from LoanApply  JOIN LoanCategory on LoanCategory.Id=LoanApply.LoanCategory  JOIN LoanRequestStatus  on LoanRequestStatus.LoanId = LoanApply.LoanApplyId   where LoanCategory='" + cat + "' ";

            SqlDataAdapter da = new SqlDataAdapter(query1,conn);
            da.Fill(dt);

           // r data = db.LoanApplies.SqlQuery(query).ToList();
            return View(dt);
        }
        public ActionResult detailsprov(int ide)
        {
           
            DataTable dt = new DataTable();
            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
            //string query = "SELECT LoanApplyId,LoanMoney,RequestDate,LoanForProperty,LoanForAutomobile from LoanApply JOIN LoanRequestStatus ON LoanRequestStatus.LoanId = LoanApply.LoanApplyId JOIN LoanCategory on LoanCategory.Id=LoanApply.LoanCategory JOIN Employee on Employee.Id = LoanApply.EmployeeId  where LoanCategory='" + cat + "' AND Employee.Email ='" + User.Identity.GetUserName().ToString() + "'";
            //va
            string query1 = "SELECT LoanApplyId,EmployeeId,Employee.FirstName + ' ' +Employee.LastName,Employee.Email,Employee.Salary,LoanMoney,RequestDate,RequestStatus,Reason,LoanForProperty,LoanForAutomobile,NoOfInstallments,[Installment Money],InstallmentStartDate,InstallmentEndDate,LoanAgreement from LoanApply JOIN Employee ON Employee.Id = LoanApply.EmployeeId   JOIN LoanCategory on LoanCategory.Id=LoanApply.LoanCategory  JOIN LoanRequestStatus  on LoanRequestStatus.LoanId = LoanApply.LoanApplyId   where LoanApplyId = '" + ide+"' ";

            SqlDataAdapter da = new SqlDataAdapter(query1, conn);
            da.Fill(dt);

EmployeeLoanManagementSystem/EmployeeLoanManagementSystem/Views/loan/Create.cshtml
@model EmployeeLoanManagementSystem.Models.LoanApply

@{
    ViewBag.Title = "Create";
}
<head>
    <style type="text/css">

        body {
        }

        .container {
            overflow: auto;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        nav.navbar.bootsnav.navbar-fixed {
            overflow: scroll;
            height: 100%;
        }

        ::-webkit-scrollbar-thumb {
            border-radius: 4px;
            background-color: rgba(0,0,0,.5);
            -webkit-box-shadow: 0 0 1px rgba(255,255,255,.5);
        }


        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>
    <script type="text/javascript">
                function instalno()
                {
                    var a = document.getElementById("loanreq").value;
                    var j = 60;
                    var c;
                    var b = parseInt(a / j);
                    if (b < 2000) {
                        c = 2000 - b;
                        b = b + c;
                    }
                    var instalacq = document.getElementById('instalacq');
                    instalacq.value = b;
                    var instalacq1 = document.getElementById('maxinstal');

                    var instalacq2 = document.getElementById('instalacq');
                    instalacq1.value = 60;


                }
                
    </script>
    <script type="text/javascript">
        function instalno1() {
            var a = document.getElementById('loanreq').value;
            var c = document.getElementById('instalmoney').value;
            document.getElementById('in').value = parseInt(a / c);
           // d.value = Math.floor(a / c);

        }
    </script>
</head>


@using (Html.BeginForm("Create","loan",FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <html>
    <body>
        <div class="container">


            <div class="col-md-8 col-md-offset-3">
                <img src="/images/syslogo.png" align="left" style="height:140px; padding-top:15px;padding-left:350px">
            </div>
            <center style="text-align:center ;
	padding-top: 130px;padding-bottom:20px"><b class="registration">LOAN APPLICATION FORM</b></center>
            <hr />
            <div class="col-lg-6 col-md-offset-3">
                <h4 align="left"> CONTACT INFORMATION</h4>
                <hr />

                <div class="form-group">
                    <h5>First Name :</h5>
                    <input type="text" name="name" value=@ViewBag.nam style="font-size: 20px;height:50px;width:550px" readonly/>
                </div>
                <div class="form-group">
                    <h5>Last Name :</h5>
                    <input type="text" name="name" value=@ViewBag.nam1 style="font-size: 20px;height:50px;width:550px" readonly />
                </div>
                <div class="form-group">
                    <h5>Email :</h5>
                    <input type="text" name="email" value=@ViewBag.em style="font-size: 20px;height:50px;width:550px" readonly/>
                </div>


                <div class="form-group">
                    <h5>Contact No  :</h5>
                    <input type="text" name="contact" value=@ViewBag.con style="font-size: 20px;height:50px;width:550px" readonly/>
                </div>
                <hr />
                <h4 align="left"> EMPLOYEE INFORMATION</h4>
                <hr />
                <div class="form-group">
                    <h5>Designation  :</h5>
                    <input type="text" name="designation" value=@ViewBag.des style="font-size: 20px;height:50px;width:550px" readonly/>
                </div>
                <div class="form-group">
                    <h5>Department  :</h5>
                    <input type="text" name="department" value=@ViewBag.dep style="font-size: 20px;height:50px;width:550px" readonly/>
                </div>
                <div class="form-group">
                    <h5>Monthly Income  :</h5>
                    <input type="text" name="income" value=@ViewBag.sal style="font-size: 20px;height:50px;width:550px" readonly/>
                </div>
                <div class="form-group">
                    <h5>Provident Fund  :</h5>
                    <input type="text" name="fund" value=@ViewBag.prov style="font-size: 20px;height:50px;width:550px" readonly/>
                </div>
                <div class="form-group">
                    <h5>Account No.  :</h5>
                    <input type="text" name="account" value=@ViewBag.acc style="font-size: 20px;height:50px;width:550px" readonly/>
                </div>
                <hr />
                <h4 align="left">APPLY FOR LOAN</h4>
                <hr />
                <div class="form-group">
                    <h5>Loan Category :</h5>
                    <br />
                    <p style="font-size: 15px">
                        Loan Against Provident Fund
                        @Html.RadioButton("Category", "AgainstProvidentFund")
                        <br />
                    <p style="font-size: 15px">
                        General Loan
                        @Html.RadioButton("Category", "General")
                        @*<input align="left" type="radio" name="provident" style="height:30px;width:50px" class="PFUND" /><p style="font-size: 15px">
                    Loan Against Provident Fund<br>
                    <input align="left" type="radio" name="general" style="height:30px;width:50px" class="General" />
                <p style="font-size: 15px">General Loan<br>*@
                </div>
                <div class="form-group">
                    <h5>Loan Purpose :</h5>
                    <br />
                    <p style="" font-size: 15px">You are required to select the category written below if you have choosen loan against provident fund</p><br />
                    <p style="font-size: 15px">Property @Html.RadioButton("Purpose", "Property")
                    <p style="font-size: 15px">
                        AutoMobile @Html.RadioButton("Purpose", "Automobile")

                </div>
                <div class="form-group">
                    <h5>Maximum General Loan Granted  :</h5>
                    <input type="number" name="maxloan" value=@ViewBag.sal style="font-size: 20px;height:50px;width:550px" readonly/>
                </div>
                <div class="form-group">
                    <h5>Maximum Loan Against Provident Fund Granted  :</h5>
                    <input type="number" name="maxloan1" value=@ViewBag.prov style="font-size: 20px;height:50px;width:550px" readonly/>
                </div>
                <div class="form-group">
                    <h5> Loan Requested  :</h5>
                    <input type="number" name="loanreq" id="loanreq" oninput="instalno()" style="font-size: 20px;height:50px;width:550px" />
                </div>

                <div class="form-group">
                    <h5> Maximum Number Of Installments  :</h5>
                    <input type="number" name="maxinstal" id="maxinstal" style="font-size: 20px;height:50px;width:550px" readonly/>
                </div>
                <div class="form-group">
                    <h5> Least Installments Money Acquired  :</h5>
                    <input type="number" name="instalacq" id="instalacq"  style="font-size: 20px;height:50px;width:550px" readonly/>
                </div>

                <div class="form-group">
                    <h5> Installments Money  :</h5>
                    <input type="number" name="instalmoney" id="instalmoney" oninput="instalno1()" style="font-size: 20px;height:50px;width:550px" />
                </div>
                <div class="form-group">
                    <h5> Number Of Installments Acquired  :</h5>
                    <input type="number" name="in" id="in" style="font-size: 20px;height:50px;width:550px" readonly/>
                </div>
                <hr />
                <h4 align="left">ACKNOWLEDGEMENT</h4>
                <hr />
                <div class="form-group">

                    <p style="" font-size: 15px">I hereby agree that the information given is true, accurate and complete as of the date of this application submission </p><br />
                    <p style="font-size: 15px">Yes<input align="left" type="radio" name="ack" style=" height:30px;width:50px" class="Male" value="Yes" />
                    <p style="font-size: 15px">No<input align="left" type="radio" name="ack" style=" height:30px;width:50px" class="Male" value="No" checked/>
                </div>
                <div class="form-group">
                    <p>The employee needs to download the template. Print it and fill it. Upload the image of the filled agreement document  in the upload button tab below</p>
                    <a href="~/LoanApplies/Download">
                        <input class="btn " style="font-family:Arial;font-size:12px;height:50px;width:160px" type="button" value="Download" />
                    </a>
                </div>
                @* @using (Html.BeginForm("docupload", "Upload Image Here", FormMethod.Post, new { enctype = "multipart/form-data" }))*@
                <div class="form-group">
                    <p>Upload the image of the filled agreement document  in the upload button tab below</p>
                    <input type="file" id="image1" name="image1" />

                </div>



                <div class="form-group">

                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />

                    </div>
                </div>
                @* @if (TempData["Success"] != null)
        {
            <p class="alert alert-success" id="successMessage">@TempData["Success"]</p>
        }*@
                <!-- <div class="form-group">
                    <a href="~/Admin/Dashboard">
                        <input class="btn " style="font-family:Arial;font-size:18px;height:50px;width:120px" type="button" value="Log In" />
                    </a>
                    <a href="~/Admin/Reset">
                        <input class="btn " style="font-family:Arial;font-size:18px;height:50px;width:150px" type="button" value="Reset Password" />
                    </a>
                </div>
            </form>
        </div>
    </div>-->
            </div>
        </div>

    </body>
</html>
}
    <div>
        @ViewBag.Error
    </div>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EmployeeLoanManagementSystem/EmployeeLoanManagementSystem/Views/loan/documentsverification.cshtml
@{
    ViewBag.Title = "documentsverification";
}


<head>
    <style type="text/css">
        <meta name="viewport" content="width=device-width, initial-scale=1" >
        <style >
        * {
            box-sizing: border-box;
        }

        body {
            font-family: Verdana, sans-serif;
        }

        .mySlides {
            display: none;
        }

        img {
            vertical-align: middle;
        }

        .image {
            opacity: 1;
            transition: .5s ease;
            backface-visibility: hidden;
        }

        .image1 {
            opacity: 1;
            transition: .5s ease;
            backface-visibility: hidden;
        }



        .image:hover {
            opacity: 0.3;
        }


        .image1:hover {
            opacity: 0.3;
        }

        .middle {
            transition: .5s ease;
            opacity: 0;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%,-50%);
            -ms-transform: translate(-50%,-50%);
            text-align: center
        }

            .middle:hover {
                opacity: 1;
            }

        .text1 {
            background-color: #4CAF50;
            color: white;
            font-size: 16px;
            padding: 16px 32px
        }
        /* Slideshow container */
        .slideshow-container {
            max-width: 1000px;
            position: relative;
            margin: auto;
        }

        /* Caption text */
        .text {
            color: #f2f2f2;
            font-size: 15px;
            padding: 8px 12px;
            position: absolute;
            bottom: 8px;
            width: 100%;
            text-align: center;
        }


        /* Number text (1/3 etc) */
        .numbertext {
            color: #f2f2f2;
            font-size: 12px;
            padding: 8px 12px;
            position: absolute;
            top: 0;
        }

        /* The dots/bullets/indicators */
        .dot {
            height: 15px;
            width: 15px;
            margin: 0 2px;
            background-color: #bbb;
            border-radius: 50%;
            display: inline-block;
            transition: background-color 0.6s ease;
        }

        .active {
            background-color: #717171;
        }

        /* Fading animation */
        .fade {
            -webkit-animation-name: fade;
            -webkit-animation-duration: 1.5s;
            animation-name: fade;
            animation-duration: 1.5s;
        }

        @@-webkit-keyframes fade {
            from {
                opacity: .4
            }

            to {
                opacity: 1
            }
        }

        @@keyframes fade {
            from {
                opacity: .4
            }

            to {
                opacity: 1
            }
        }

        /* On smaller screens, decrease text size */
        @@media only screen and (max-width: 300px) {
            .text {
                font-size: 11px
            }
        }

        body {
        }

        .container {
            overflow: auto;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        nav.navbar.bootsnav.navbar-fixed {
            overflow: scroll;
            height: 100%;
        }

        .HEADING:hover {
            color: cadetblue
        }

        ::-webkit-scrollbar-thumb {
            border-radius: 4px;
            background-color: rgba(0,0,0,.5);
            -webkit-box-shadow: 0 0 1px rgba(255,255,255,.5);
        }

        .a:hover {
            background-color: #009688;
        }

        .w3-teal {
            height: 50px;
        }

        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>

</head>


<h2 style="padding-top:50px;padding-left:300px;color:#009688">WELCOME TO LOAN PROVIDER SYSTEM</h2>
<!DOCTYPE html>
<html>
<title>W3.CSS</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>

    <div class="w3-sidebar w3-bar-block w3-card w3-animate-left" style="display:none;height:500px" id="mySidebar">
        <button class="w3-bar-item w3-button w3-large"
                onclick="w3_close()">

            Close &times;

        </button>
        <br />
        <a href=@Url.Action("loanpolicies", "loan") class="a">Loan Policies</a><br><br><br>
        <a href=@Url.Action("instructions", "loan") class="a">Apply For Loan</a><br><br><br>
        <a href="" class="a">Loan History</a><br><br><br>
        <a href="#" class="a">Loan Status</a><br><br><br>
    </div>

    <div id="main">

        <div class="w3-teal">
            <button id="openNav" class="w3-button w3-teal w3-xlarge" style="" onclick="w3_open()">&#9776;</button>
            <div class="w3-container">
                @*<h3 style="padding-top:50px">LOAN CATEGORY</h3>*@
            </div>
        </div>
        <div class="w3-container">
            <b>
                <p style="font-size:16px ;color: #009688;padding-bottom:20px">
                    Choose the loan category in which you want to view your loan status
                </p>
            </b>
        </div>

    </div>
    @Html.BeginForm("documentsverification", "loan", FormMethod.Post,
             new{ enctype="multipart/form-data"})
    {
    @Html.AntiForgeryToken()
    <div class="container" style="width: 100%;">
        <div class="theme-table-image col-sm-6" style="">

            <img src="/images/kang4.jpg" style="height:250px;width:550px" class="image">


            <H4 style="text-align:center" class="HEADING">PROPERTY LOAN</H4>
            <p>If you have opted loan against provident fund for property,submit the scanned image of the document. </p>

            <input type="file" id="imageproperty" name="imageproperty" style="padding-bottom:10px" />




        </div>

        <div class="theme-table-image col-sm-offset-6">

            <img src="/images/autoloan.jpg" style="height:250px;width:550px" class="image1">


            <h4 style="text-align:center" class="HEADING">AUTOMOBILE LOAN </h4>

            <p>If you have opted loan against provident fund for property,submit the scanned image of the document. </p>

            <input type="file" id="imageauto" name="imageauto" style="padding-bottom:10px" />


        </div>
    </div>
    <div class="form-group">

        <div class="col-md-offset-4 col-md-10">
            <input type="submit" value="Submit Document" class="btn btn-default" />

        </div>
    </div>
    }

    <div class="w3-container">
        <b>

        </b>
    </div>



    <script>
        function w3_open() {
            document.getElementById("main").style.marginLeft = "25%";
            document.getElementById("mySidebar").style.width = "25%";
            document.getElementById("mySidebar").style.display = "block";
            document.getElementById("openNav").style.display = 'none';
        }
        function w3_close() {
            document.getElementById("main").style.marginLeft = "0%";
            document.getElementById("mySidebar").style.display = "none";
            document.getElementById("openNav").style.display = "inline-block";
        }
    </script>

</body>

</html>

EmployeeLoanManagementSystem/EmployeeLoanManagementSystem/Views/loan/general.cshtml
@model System.Data.DataTable
@{
    ViewBag.Title = "general";
}

<h2>General Loan</h2>

<head>
    <style>
        nav.navbar.bootsnav.navbar-fixed {
            overflow: scroll;
            height: 100%;
        }
    </style>
</head>


<table class="table table-bordered table-striped">
    <tr>
        <th >
            Loan Apply Id
        </th>
        <th>Loan Money</th>
        <th>Request Date</th>
        <th>Loan Request Status</th>
        <th>Reason</th>
        <th>Edit Loan</th>
        <th>View Installments</th>
    </tr>
    @for (int i = 0; i < Model.Rows.Count; i++)
    {
    <tr>
        <td >@Model.Rows[i][0]</td>
        <td>@Model.Rows[i][1]</td>
        <td>@Model.Rows[i][2]</td>
        <td>@Model.Rows[i][3]</td>
        <td>@Model.Rows[i][4]</td>
        <td>@Html.ActionLink("Edit", "Edit", "loan", new { @ide = Model.Rows[i][0] },null)</td>
        <td>@Html.ActionLink("View Installments", "instal", "loan", new { @ide = Model.Rows[i][0] },null)</td>
    </tr>
    }
</table>

EmployeeLoanManagementSystem/EmployeeLoanManagementSystem/Views/loan/instal.cshtml
@{
    ViewBag.Title = "instal";
}

<head>
    <style>
        nav.navbar.bootsnav.navbar-fixed {
            overflow: scroll;
            height: 100%;
        }
    </style>
</head>
<h2 style="padding-top:100px;text-align:center">Installments</h2>
<table class="table table-bordered table-striped">
    <tr>

        <th>Installment Number</th>
        <th>Installment Money</th>
        <th>Installment Date</th>
        <th>Is Paid</th>

    </tr>
    @for (int i = 0; i < Model.Rows.Count; i++)
    {
        <tr>

            <td>@Model.Rows[i][0]</td>
            <td>@Model.Rows[i][1]</td>
            <td>@Model.Rows[i][2]</td>
            <td>@Model.Rows[i][3]</td>

        </tr>
    }
</table>