EmployeeLoanManagementSystem/EmployeeLoanManagementSystem/Controllers/LoanApplicationController.cs
using EmployeeLoanManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeLoanManagementSystem.Controllers
{
    public class LoanApplicationController : Controller
    {
        SqlConnection conn = new SqlConnection("Data Source=DESKTOP-R6RA1PL\\TOOBAASIF;Initial Catalog=DB7;User ID=sa;Password=1212;MultipleActiveResultSets=True;Application Name=EntityFramework");

        // GET: LoanApplication
        public ActionResult Index()
        {
            return View();
        }

        // GET: LoanApplication/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        private int emp_id(string email1)
        {
            string query;
            query = "SELECT Id FROM Employee WHERE  Email ='" + email1 + "' ";

            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
            SqlCommand cmd = new SqlCommand(query, conn);
            SqlDataReader reader = cmd.ExecuteReader();
            int value = 0;
            while (reader.Read())
            {
                value = int.Parse(reader[0].ToString());
            }
            return value;
        }
        private int cat_id(string email1)
        {
            string query;
            query = "SELECT Id FROM LoanCategory WHERE  Category ='" + email1 + "' ";

            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
            SqlCommand cmd = new SqlCommand(query, conn);
            SqlDataReader reader = cmd.ExecuteReader();
            int value = 0;
            while (reader.Read())
            {
                value = int.Parse(reader[0].ToString());
            }
            return value;
        }
        // GET: LoanApplication/Create
        [HttpGet]
        public ActionResult Create()
        {
            if (conn.State == ConnectionState.Closed)
            {
                conn.Open();
            }
          //  if(provident)
           // int id1 = emp_id(email);
            //String qry = "insert into LoanApply  values('" + id1 + "','" + LastName + "','" + Contact + "','" + Email + "','" + dt + "','" + gen + "' ) ";
           // SqlCommand sc = new SqlCommand(qry, conn);
           // int i = sc.ExecuteNonQuery();
            return View();
        }
        //file download
        public FileResult Download()
        {
            string path = Server.MapPath("~/assets/files");
            string filename = Path.GetFileName("agreement.pdf");
            string fullpath = Path.Combine(path, filename);
            return File(fullpath, "pdf", "employee_agreement.pdf");

            //return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }
        // POST: LoanApplication/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
       
        public ActionResult Create(FormCollection collection,byte[]image1)
        {
          //  try
            //{
                if (conn.State == ConnectionState.Closed)
                {
                    conn.Open();
                }
            int loanreq = int.Parse(collection["loanreq"]);
            int instalacq = int.Parse(collection["instalacq"]);
            DateTime enddate = DateTime.Parse(collection["enddate"]);
            DateTime startdate = DateTime.Parse(collection["startdate"]);
           int  instal = (instalacq);
                decimal loan1 = loanreq;
            string email = collection["email"].ToString();
            decimal instalmoney = decimal.Parse(collection["instalmoney"]);
                int catid=0;
                // TODO: Add insert logic here
                string email1 = email;
                int emailid = emp_id(email1);
              //  string loan_mon = ;
              //  int  = emp_id(email1);
                string loancategory = collection["Category"].ToString();
                if(loancategory == "AgainstProvidentFund")
                {
                    string l = "Against Provident Fund";
                    catid = cat_id(l);
                }
                else if(loancategory == "General")
                {
                    string l = "General Loan";
                    catid = cat_id(l);
                }
                DateTime req = DateTime.Now;
                string choose = "N";
                string choose1 = "Y";
                string loanpur = collection["Purpose"].ToString();
                if (loancategory == "Automobile")
                {
                    String qry = "insert into LoanApply  values('" + emailid + "','" + catid + "','" + loan1 + "','" + instal + "','" + startdate + "','" + enddate+ "','" + req + "','" + image1 + "','" + choose + "','" + choose1 + "','" + instalmoney + "' ) ";
                    SqlCommand sc = new SqlCommand(qry, conn);
                    int i = sc.ExecuteNonQuery();
                }
                else if(loancategory == "Property")
                {
                    String qry = "insert into LoanApply  values('" + emailid + "','" + catid + "','" + loan1 + "','" + instal + "','" + startdate + "','" + enddate + "','" + req + "','" + image1 + "','" + choose1 + "','" + choose + "','" + instalmoney + "' ) ";
                    SqlCommand sc = new SqlCommand(qry, conn);
                    int i = sc.ExecuteNonQuery();
                }
                else
                {
                    String qry = "insert into LoanApply  values('" + emailid + "','" + catid + "','" + loan1 + "','" + instal + "','" + startdate + "','" + enddate + "','" + req + "','" + image1 + "','" + choose + "','" + choose + "','" + instalmoney + "' ) ";
                    SqlCommand sc = new SqlCommand(qry, conn);
                    int i = sc.ExecuteNonQuery();
                    if (i >= 1)
                    { ViewBag(); }
                    else
                    {
                         }
                }
                    return RedirectToAction("Index");
            //}
           /* catch
            {
                return View();
            }*/
        }

        // GET: LoanApplication/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: LoanApplication/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: LoanApplication/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: LoanApplication/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

EmployeeLoanManagementSystem/EmployeeLoanManagementSystem/Views/LoanApplication/Create.cshtml
@model EmployeeLoanManagementSystem.Models.LoanApply

@{
                /**/

                /**/

                ViewBag.Title = "Create";

}


<html>


<head>



    <style type="text/css">

        body {
        }

        .container {
            overflow: auto;
        }

        .registration {
            color: black;
            font-size: 40px;
            font-family: Agency FB;
            font-weight: 700;
            border-bottom-style: ridge;
        }

        .row {
        }

        nav.navbar.bootsnav.navbar-fixed {
            overflow: scroll;
            height: 100%;
        }

        ::-webkit-scrollbar-thumb {
            border-radius: 4px;
            background-color: rgba(0,0,0,.5);
            -webkit-box-shadow: 0 0 1px rgba(255,255,255,.5);
        }


        .btn.hover {
            background-color: aqua;
        }

        label {
            font-size: 22px;
        }

        .btn-danger {
            border-radius: 0px;
        }
    </style>

</head>
<body>
    <div class="container">


        <div class="col-md-8 col-md-offset-3">
            <img src="/images/syslogo.png" align="left" style="height:140px; padding-top:15px;padding-left:350px">
        </div>
        <center style="text-align:center ;
	padding-top: 130px;padding-bottom:20px"><b class="registration">LOAN APPLICATION FORM</b></center>
        <hr />
        <div class="col-lg-6 col-md-offset-3">
            <h4 align="left"> CONTACT INFORMATION</h4>
            <hr />

            <div class="form-group">
                <h5>Name :</h5>
                <input type="text" name="name" style="font-size: 20px;height:50px;width:550px" />
            </div>
            <div class="form-group">
                <h5>Email :</h5>
                <input type="text" name="email" style="font-size: 20px;height:50px;width:550px" />
            </div>
            <div class="form-group">
                <h5>Gender :</h5>

                <input align="left" type="radio" name="male" style="font-size: 18px;background-color:white; height:30px;width:50px" class="Male" /><p style="font-size: 15px">Male</p> <br>
                <input align="left" type="radio" name="female" style="font-size: 18px;background-color:white; height:30px;width:50px" class="Female" /><p style="font-size: 15px">Female</p><br>
            </div>
            <div class="form-group">
                <h5>Date of Birth :</h5>
                <input type="datetime" name="birth" style="font-size: 20px;height:50px;width:550px" />
            </div>
            <div class="form-group">
                <h5>Address :</h5>
                <input type="text" name="address" style="font-size: 20px;height:50px;width:550px" />
            </div>
            <div class="form-group">
                <h5>Contact No  :</h5>
                <input type="text" name="contact" style="font-size: 20px;height:50px;width:550px" />
            </div>
            <hr />
            <h4 align="left"> EMPLOYEE INFORMATION</h4>
            <hr />
            <div class="form-group">
                <h5>Designation  :</h5>
                <input type="text" name="designation" style="font-size: 20px;height:50px;width:550px" />
            </div>
            <div class="form-group">
                <h5>Department  :</h5>
                <input type="text" name="department" style="font-size: 20px;height:50px;width:550px" />
            </div>
            <div class="form-group">
                <h5>Monthly Income  :</h5>
                <input type="text" name="income" style="font-size: 20px;height:50px;width:550px" />
            </div>
            <div class="form-group">
                <h5>Provident Fund  :</h5>
                <input type="text" name="fund" style="font-size: 20px;height:50px;width:550px" />
            </div>
            <div class="form-group">
                <h5>Account No.  :</h5>
                <input type="text" name="account" style="font-size: 20px;height:50px;width:550px" />
            </div>
            <hr />
            <h4 align="left">APPLY FOR LOAN</h4>
            <hr />
            <div class="form-group">
                <h5>Loan Category :</h5>
                <br />
                <p style="font-size: 15px">
                    Loan Against Provident Fund
                    @Html.RadioButton("Category", "AgainstProvidentFund")
                    <br />
                <p style="font-size: 15px">
                    General Loan
                    @Html.RadioButton("Category", "General")
                    @*<input align="left" type="radio" name="provident" style="height:30px;width:50px" class="PFUND" /><p style="font-size: 15px">
                    Loan Against Provident Fund<br>
                    <input align="left" type="radio" name="general" style="height:30px;width:50px" class="General" />
                <p style="font-size: 15px">General Loan<br>*@
            </div>
            <div class="form-group">
                <h5>Loan Purpose :</h5>
                <br />
                <p style="" font-size: 15px">You are required to select the category written below if you have choosen loan against provident fund</p><br />
                <p style="font-size: 15px">Property @Html.RadioButton("Purpose", "Property")
                <p style="font-size: 15px">
                    AutoMobile @Html.RadioButton("Purpose", "Automobile")
                   
            </div>
            <div class="form-group">
                <h5>Maximum Loan Granted  :</h5>
                <input type="number" name="maxloan" style="font-size: 20px;height:50px;width:550px" />
            </div>
            <div class="form-group">
                <h5> Loan Requested  :</h5>
                <input type="number" name="loanreq" style="font-size: 20px;height:50px;width:550px" />
            </div>
            <div class="form-group">
                <h5> Maximum Number Of Installments  :</h5>
                <input type="number" name="maxinstal" style="font-size: 20px;height:50px;width:550px" />
            </div>
            <div class="form-group">
                <h5> Installments Acquired  :</h5>
                <input type="number" name="instalacq" style="font-size: 20px;height:50px;width:550px" />
            </div>
            <div class="form-group">
                <h5> Installments Start Date  :</h5>
                <input type="datetime" name="startdate" style="font-size: 20px;height:50px;width:550px" />
            </div>
            <div class="form-group">
                <h5> Installments End Date  :</h5>
                <input type="datetime" name="enddate" style="font-size: 20px;height:50px;width:550px" />
            </div>
            <div class="form-group">
                <h5> Installments Money  :</h5>
                <input type="number" name="instalmoney" style="font-size: 20px;height:50px;width:550px" />
            </div>
            <hr />
            <h4 align="left">ACKNOWLEDGEMENT</h4>
            <hr />
            <div class="form-group">

                <p style="" font-size: 15px">I hereby agree that the information given is true, accurate and complete as of the date of this application submission </p><br />
                <p style="font-size: 15px">Yes<input align="left" type="radio" name="ack" style=" height:30px;width:50px" class="Male" />
            </div>
            <div class="form-group">
                <p>The employee needs to download the template. Print it and fill it. Upload the image of the filled agreement document  in the upload button tab below</p>
                <a href="~/LoanApplies/Download">
                    <input class="btn " style="font-family:Arial;font-size:12px;height:50px;width:160px" type="button" value="Download" />
                </a>
            </div>
            <div class="form-group">
                <p>Upload the image of the filled agreement document  in the upload button tab below</p>
                <input type="file" id="image1" name="image1" />

            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <a href=@Url.Action("Create","LoanApplication")>Submit@*~/LoanApplication/Create">
                        <input type="submit" value="Create" class="btn btn-default" />*@
                    </a>
                </div>
            </div>
            <!-- <div class="form-group">
                    <a href="~/Admin/Dashboard">
                        <input class="btn " style="font-family:Arial;font-size:18px;height:50px;width:120px" type="button" value="Log In" />
                    </a>
                    <a href="~/Admin/Reset">
                        <input class="btn " style="font-family:Arial;font-size:18px;height:50px;width:150px" type="button" value="Reset Password" />
                    </a>
                </div>
            </form>
        </div>
    </div>-->
        </div>
    </div>

</body>
</html>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}